### ISSUE TITLE
Add alameda as loader option

### ISSUE THREAD

**Issue by fragsalat** [aurelia/cli#1001]
**I'm submitting a feature request**

* **Library Version:**
all

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
all

* **NPM Version:**
all

* **Browser:**
all

* **Language:**
all

* **Loader/bundler:**
RequireJS / Alameda

**Current behavior:**
Right now the cli tool allows to select requirejs as loader.

* **What is the expected behavior?**
It should be possible for the user to select alameda or requirejs as default loader.

* **What is the motivation / use case for changing the behavior?**
Alameda targets modern browsers by utilizing Promises instead of interval cycles which improves the performance of the application.

**Todo**:
- [ ] Replace requirejs option with AMD Loader
- [ ] Add another step to select requirejs or alameda
- [ ] Distinguish in require templates between requirejs and alameda
- [ ] aurelia-karma.js must adopt more generic approach to prepend /base/ to urls by proxying nameToUrl function instead of requirejs.load and global.define. Alameda doesn't have requirejs.load

**Comment by fragsalat** [comment]
Question to the code owner, why did you overwrote requirejs.load and created a custom normalize path function? It looks like you only wanted to add /base/ to all urls during test setup?
https://github.com/aurelia/cli/blob/master/lib/resources/test/require.aurelia-karma.js#L47

As far as I tested it and had a look it would be absolutely sufficient to do the following instead
```js
    const origToUrl = requirejs.nameToUrl;
    requirejs.nameToUrl = function extendedToUrl(moduleName) {
      let url = origToUrl(moduleName);
      if (url.indexOf('/base') !== 0) {
        url = `/base/${url}`;
      }
      return url;
    };
```

**Comment by fragsalat** [comment]
Not yet. I'll first intregrate alameda sucessfully in my work's project and based on that create a PR here :)
